# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('maximum_rabi_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('polar_angle', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pulse_type', models.CharField(choices=[('primitive', 'primitive'), ('corpse', 'corpse'), ('gaussian', 'gaussian'), ('cinbb', 'cinbb'), ('cinsk', 'cinsk')], max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
